Repository BibliothequeSainteGenevieve/cabestan, pull requests merged in 2025-02, with the labels that each got.

#1 Setup client
  .vscode/settings.json
  .vscode/tailwind.json
  client/components.json
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/App.css
  client/src/App.tsx
  client/src/i18n/config.ts
  client/src/i18n/fr.json
  client/src/index.css
  client/src/lib/utils.ts
  client/tailwind.config.js
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  docker/Makefile
  docker/docker-compose.yml
  docker/wiremock/mappings/test.json
Labels: enhancement

#3 feat: header component
  client/.editorconfig
  client/eslint.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/assets/logo-bsg.png
  client/src/assets/react.svg
  client/src/components/Header.tsx
  client/src/i18n/fr.json
  client/src/index.css
  client/src/pages/HomePage.tsx
  client/tailwind.config.js
Labels: enhancement, front

#4 chore: remove @thetribe ESLint configuration and update ESLint config
  client/eslint.config.js
  client/package-lock.json
  client/package.json
Labels: bug, front

#6 test: add mock
  docker/wiremock/mappings/book/export.json
  docker/wiremock/mappings/book/search.json
  docker/wiremock/mappings/config/client.json
  docker/wiremock/mappings/rcr/export.json
  docker/wiremock/mappings/rcr/graph.json
  docker/wiremock/mappings/rcr/maps.json
  docker/wiremock/mappings/rcr/search.json
  docker/wiremock/mappings/rcr/suggestion.json
Labels: documentation, ops

#7 Feat/bootstrap backend
  app/cabestan/api.py
  app/cabestan/settings.py
  app/cabestan/urls.py
  app/entrypoint.sh
  app/requirements.txt
  app/rest/__init__.py
  app/rest/admin.py
  app/rest/api.py
  app/rest/apps.py
  app/rest/fixtures/book_types.json
  app/rest/fixtures/country_types.json
  app/rest/fixtures/departments.json
  app/rest/fixtures/languages.json
  app/rest/fixtures/rcr_types.json
  app/rest/fixtures/regions.json
  app/rest/migrations/0001_initial.py
  app/rest/migrations/__init__.py
  app/rest/models.py
  app/rest/serializers.py
  app/rest/tests.py
  app/rest/urls.py
  app/rest/views.py
  app/scraper/api_schema.py
  docker/docker-compose.yml
  docker/nginx/cabestan.conf.model
  docker/wiremock/mappings/rcr/suggestion.json
Labels: enhancement, ops, backend

#13 Front/searchbar
  client/eslint.config.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/index.ts
  client/src/components/Header.tsx
  client/src/components/SearchBar/ComboboxFilter.tsx
  client/src/components/SearchBar/ComboboxSearchFilter/ComoboxSearchFilter.tsx
  client/src/components/SearchBar/ComboboxSearchFilter/Suggestions.tsx
  client/src/components/SearchBar/ComboboxSearchFilter/Value.tsx
  client/src/components/SearchBar/DateRangePicker/DateRangePicker.tsx
  client/src/components/SearchBar/DateRangePicker/PopoverWithDropdownCalendar.tsx
  client/src/components/SearchBar/PopoverMoreFilters.tsx
  client/src/components/SearchBar/SearchBar.tsx
  client/src/components/SearchBar/SearchInput/SearchInput.tsx
  client/src/components/SearchBar/SearchInput/Suggestions.tsx
  client/src/components/ui/button.tsx
  client/src/components/ui/calendar.tsx
  client/src/components/ui/command.tsx
  client/src/components/ui/dialog.tsx
  client/src/components/ui/input.tsx
  client/src/components/ui/popover.tsx
  client/src/hooks/useDebounce.ts
  client/src/hooks/useSetFilterSearchParams.ts
  client/src/i18n/fr.json
  client/src/index.css
  client/src/layouts/LayoutBase.tsx
  client/src/models/Filters.ts
  client/src/pages/HomePage.tsx
  client/tailwind.config.js
  docker/docker-compose.yml
  docker/wiremock/mappings/config/client.json
  docker/wiremock/mappings/rcr/publisher-detail.json
  docker/wiremock/mappings/rcr/publishers-suggestion.json
  docker/wiremock/mappings/rcr/suggestion.json
  docker/wiremock/mappings/test.json
Labels: enhancement, front

#14 Villes avec suggestions
  client/package.json
  client/src/App.tsx
  client/src/api/index.ts
  client/src/components/SearchBar/ComboboxSearchFilter/ComboboxSearchFilter.tsx
  client/src/components/SearchBar/ComboboxSearchFilter/Suggestions.tsx
  client/src/components/SearchBar/ComboboxSearchFilter/Value.tsx
  client/src/components/SearchBar/SearchBar.tsx
  client/src/components/SearchBar/SearchInput/SearchInput.tsx
  client/src/components/SearchBar/SearchInput/Suggestions.tsx
  client/src/i18n/fr.json
  client/src/models/Suggestions.ts
  docker/wiremock/mappings/cities/cities-detail.json
  docker/wiremock/mappings/cities/cities-suggestion.json
  docker/wiremock/mappings/publishers/publisher-detail.json
  docker/wiremock/mappings/publishers/publishers-suggestion.json
Labels: enhancement, front

#15 feat: Add global search suggestions endpoint with multi-type results
  app/rest/api.py
Labels: enhancement, backend

#18 Results list with count and pagination
  client/package-lock.json
  client/package.json
  client/src/api/index.ts
  client/src/components/LoadingSpinner.tsx
  client/src/components/Pagination.tsx
  client/src/components/RCRList.tsx
  client/src/components/ResultsCount.tsx
  client/src/components/SearchBar/SearchInput/SearchInput.tsx
  client/src/components/ui/card.tsx
  client/src/components/ui/select.tsx
  client/src/i18n/fr.json
  client/src/models/RCR.ts
  client/src/pages/HomePage.tsx
  docker/wiremock/mappings/rcr/search.json
Labels: enhancement, front

#19 Front/translations update
  client/src/components/SearchBar/ComboboxFilter.tsx
  client/src/i18n/fr.json
Labels: enhancement, front

#20 fix: bookstypes filter becomes documentstypes
  app/rest/views.py
  client/src/api/index.ts
  client/src/components/SearchBar/SearchBar.tsx
  client/src/i18n/fr.json
  client/src/models/Filters.ts
  docker/wiremock/mappings/config/client.json
Labels: bug, front

#24 Fix/search input
  client/src/components/Pagination.tsx
  client/src/components/SearchBar/ComboboxSearchFilter/Suggestions.tsx
  client/src/components/SearchBar/SearchInput/SearchInput.tsx
  client/src/components/SearchBar/SearchInput/Suggestions.tsx
  client/src/hooks/useClickOutside.ts
  client/src/hooks/useSetFilterSearchParams.ts
  docker/docker-compose.yml
Labels: bug, front

#25 feat: Enhance RCR search with publication and reedition date filters
  app/rest/api.py
Labels: bug, enhancement, backend

#27 Feat/count book by filter
  app/rest/api.py
Labels: enhancement, backend

#29 Front/filters-fixes
  client/src/api/index.ts
  client/src/components/SearchBar/ComboboxSearchFilter/ComboboxSearchFilter.tsx
  client/src/components/SearchBar/ComboboxSearchFilter/Suggestions.tsx
  client/src/components/SearchBar/SearchInput/Suggestions.tsx
  client/src/i18n/fr.json
  client/src/models/Suggestions.ts
  client/src/pages/HomePage.tsx
Labels: bug, front

#30 fix: update French regions list with region numeric codes
  client/src/i18n/fr.json
Labels: front

#32 feat: Enhance API response structure for search and get endpoints
  app/rest/api.py
Labels: enhancement, backend

#33 feat: Add map view with Leaflet and marker clustering
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/api/index.ts
  client/src/assets/landmark.svg
  client/src/components/Map/Map.css
  client/src/components/Map/Map.tsx
  client/src/components/Map/MapContent.tsx
  client/src/components/Pagination.tsx
  client/src/i18n/fr.json
  client/src/models/RCR.ts
  client/src/pages/HomePage.tsx
Labels: enhancement, front

#34 Front/filters with suggestions
  client/src/api/index.ts
  client/src/components/Map/Map.tsx
  client/src/components/SearchBar/ComboboxSearchFilter/ComboboxSearchFilter.tsx
  client/src/components/SearchBar/ComboboxSearchFilter/Value.tsx
Labels: bug, front

#36 Front/graph
  client/package-lock.json
  client/package.json
  client/src/components/Chart.tsx
  client/src/components/Map/Map.css
  client/src/components/Map/MapContent.tsx
  client/src/components/Map/index.tsx
  client/src/components/SearchBar/ComboboxSearchFilter/index.tsx
  client/src/components/SearchBar/DateRangePicker/index.tsx
  client/src/components/SearchBar/SearchInput/index.tsx
  client/src/components/SearchBar/index.tsx
  client/src/components/ui/chart.tsx
  client/src/i18n/fr.json
  client/src/pages/HomePage.tsx
Labels: enhancement, front

#38 Front/performance
  client/src/components/BarsChart/BarsChart.css
  client/src/components/BarsChart/index.tsx
  client/src/components/Map/index.tsx
  client/src/components/Pagination.tsx
  client/src/components/SearchBar/PopoverMoreFilters.tsx
  client/src/components/SearchBar/SearchInput/index.tsx
  client/src/components/SearchBar/index.tsx
  client/src/components/ui/command.tsx
  client/src/i18n/fr.json
  client/src/layouts/LayoutBase.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/HomePage/Results.tsx
  client/src/pages/HomePage/index.tsx
Labels: enhancement, front

#40 Front/updates
  .vscode/tailwind.json
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/components/BarsChart/index.tsx
  client/src/components/Map/index.tsx
  client/src/components/Pagination.tsx
  client/src/components/RCRList.tsx
  client/src/components/SearchBar/DateRangePicker/Calendar.tsx
  client/src/components/SearchBar/DateRangePicker/PopoverWithDropdownCalendar.tsx
  client/src/components/ui/button.tsx
  client/src/components/ui/calendar.tsx
  client/src/components/ui/card.tsx
  client/src/components/ui/chart.tsx
  client/src/components/ui/command.tsx
  client/src/components/ui/dialog.tsx
  client/src/components/ui/input.tsx
  client/src/components/ui/popover.tsx
  client/src/components/ui/select.tsx
  client/src/index.css
  client/src/pages/HomePage/Results.tsx
  client/src/pages/HomePage/index.tsx
  client/tailwind.config.js
  client/vite.config.ts
Labels: front

#42 Front/export
  client/src/api/index.ts
  client/src/components/BarsChart/index.tsx
  client/src/components/Map/Map.css
  client/src/components/Map/MapContent.tsx
  client/src/components/Map/index.tsx
  client/src/components/RCRExport.tsx
  client/src/components/ui/button.tsx
  client/src/i18n/fr.json
  client/src/pages/HomePage/Results.tsx
  client/src/pages/HomePage/index.tsx
Labels: enhancement, front

#43 Front/robots and favicon
  client/index.html
  client/public/bsg-fav.png
  client/public/robots.txt
Labels: enhancement, front

#44 feat: Add reset filters button with tooltip in search bar
  client/package-lock.json
  client/package.json
  client/src/components/SearchBar/ResetFiltersButton.tsx
  client/src/components/SearchBar/index.tsx
  client/src/components/ui/tooltip.tsx
  client/src/i18n/fr.json
Labels: enhancement, front

#48 Front/books page base
  .gitignore
  client/src/App.tsx
  client/src/api/index.ts
  client/src/components/Header.tsx
  client/src/components/Map/index.tsx
  client/src/components/RCRDetails.tsx
  client/src/components/RCRList.tsx
  client/src/components/SearchBar/BookSearchBar.tsx
  client/src/components/SearchBar/ComboboxFilter.tsx
  client/src/components/SearchBar/PopoverMoreFilters.tsx
  client/src/components/SearchBar/RCRSearchBar.tsx
  client/src/components/SearchBar/ResetFiltersButton.tsx
  client/src/components/SearchBar/SearchInput/Suggestions.tsx
  client/src/components/SearchBar/SearchInput/index.tsx
  client/src/components/ui/button.tsx
  client/src/hooks/useSetFilterSearchParams.ts
  client/src/i18n/fr.json
  client/src/index.css
  client/src/models/Filters.ts
  client/src/pages/HomePage/index.tsx
  client/src/pages/RCRPage.tsx
  client/src/pages/routes.tsx
Labels: enhancement, front
